#
# The gitlab CI script for luSolve
#

stages:
  - setup
  - build
  - test

setup_job:
  stage: setup
  script:
    - stack setup
  tags:
    - stack-runner
  when: manual

build_job:
  stage: build
  script:
    - stack build --pedantic
  tags:
    - stack-runner

test_job:
  stage: test
  script:
    - stack test --pedantic
  tags:
    - stack-runner
